name: Deploy Django to AWS EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Navigate to the backend directory
            cd ~/PCA_BACKEND-main
            
            # Pull latest code
            git pull origin main
            
            # Activate virtual environment, install dependencies, migrate
            source venv/bin/activate
            pip install -r requirements.txt
            python manage.py makemigrations
            python manage.py migrate
            
            # Restart Gunicorn (or systemd service)
            sudo systemctl restart gunicorn
